### ISSUE TITLE
Implement user settings menu on home screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#10]
The home screen settings menu opens when the user taps on the settings in the top right of the home screen (https://github.com/OpenSRP/opensrp-client-tbr/issues/9). The user can log out of the application or change languages from this screen.

**Not Configurable**
- [x] Log out button is required. The app data remains on the device when the user logs out.

**Configurable**
- [x] Language. If the app has more than one language, they'd be able to switch between languages here. If the app only has one language, this dropdown becomes a log out button only.

![home-dropdown](https://user-images.githubusercontent.com/1584163/32496304-cfec88c2-c396-11e7-9dcd-b3bc6e0f23c0.png)

**Comment by kwasim** [comment]
The tickets #8, #9 and #10 looks good to us

**Comment by cagulas** [comment]
No issues found in QA. This lgtm.

**Comment by cagulas** [comment]
Results from QA on 19 January (v0.0.4 alpha release):

No issues, lgtm.
