### ISSUE TITLE
Set up the testing environment

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-tbr#12]
- [x] Set up testing build configuration
- [x] Set up Jacoco reporting 
- [x] Set up coveralls for test report analysis
- [x] Add testing badges to READ ME

**Comment by cagulas** [comment]
@ndegwamartin Can this be closed?

**Comment by cagulas** [comment]
@ndegwamartin I'm closing this. Please reopen if needed.
