### ISSUE TITLE
Implement the user configurable Presumptive Patients Register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#25]
The presumptive patients register screen is what you see when you select the first register listed on the home screen (https://github.com/OpenSRP/opensrp-client-tbr/issues/9).

**Not Configurable**
- [x] Pressing the back button on the tablet returns the user to the home screen https://github.com/OpenSRP/opensrp-client-tbr/issues/9. Back arrow does the same thing.
- [x] The search bar is required, but the search parameters are configurable (see the configurable section below).
- [x] In the screening xlsform (https://ona.io/opensrp/45150/246298#/settings), there is a variable called `presumptive`. This will be a required field, i.e. all projects will need to ensure that their screening form has a field that is called this. If the field evaluates to "yes" then the patient appears in the presumptive register. If the field evaluates to "no", then the patient does not get added to the register, but they should get added to a table in the DB for reference. 
- [x] If a patient gets added to the register, then the content that appears for them is determined by the columns that they choose to add to the register (issue to be created).
~~- The blue bar at the top of the `Encounter` column in the mockup below indicates the column that the register list is sorted on. This should be added last and only if it's within scope.~~ **RW: removed  from initial scope. You can check which column is being sorted on by going to the *Sort by* option in the dropdown menu.**
~~- [ ] @rowo Are we allowing the background color(s) to be configurable? I mean the blue and the dark grey bars at the top.~~ **RW: No, I don't think it's necessary now.**

**Configurable**
- [x] The name of the register is configurable - so what they name the register on the home screen should be displayed here as the register name.
- [x] The drop down menu is semi-configurable - what appears within it.
  - [x] *Add new patient* is the only required item in the list for the Presumptive Register. It opens the TB screening form (https://ona.io/opensrp/45150/246298). The name of the xlsform can be configurable, so there has to be some mechanism for the user to specify which xlsform they upload should be placed here. The name of the xlsform comes from the settings tab, the `form_title` label.
  - [x] If *Sort by* exists, app creators can choose what can be sorted on. It is not a requirement that it appears in the columns below.
  - [x] If *Filter by* exists, app creators can choose which parameters are filterable. This is a placeholder for now. Need to discuss what the filter parameters would be.
  - [x] If *Advanced search* exists, user can click to open a new full screen interaction where user can do a project database lookup on certain parameters (TBD). For now, this can be a placeholder. If they choose not to have global lookup, then they'd only have access to the patients they register themselves on their tablet. The advanced search would look and function like the one in ZEIR right now (but this can be done later).
- [x] The search bar text (where it says "Search name or ID") is configurable - so they can update the text to whatever their search parameters are. @rowo Should this text have a character limit, and if so, can we make it so that the character limit is determined by whether the search bar is half the screen or full width of the screen (i.e. they are not using the QR code scan option). **RW: We can leave character length up to the user but suggest something in the instructions.**
- [x] The search parameters are configurable - so they can select which variables from their xlsforms are searchable. If possible to add a constraint, so that they can only add parameters that are viewed on the main register screen, that would be ideal. **RW: I don't know what the current parameters are... it might be good to say only what's in the Patient info column.** 
- [x] The Scan QR Code button is configurable - they can have it or not. If they have it, the QR code scan would read the embedded ID or information in the QR code and return any matching records. If they choose not to have the QR code scan option, then the search bar can take the full width of the row. **RW: this is a global-app-level configuration. If QR codes exist in the app, then it will be included in the search bar non-configurable.**

<img src="https://user-images.githubusercontent.com/1584163/32115595-67652e32-bb15-11e7-821e-64f9f3fc2abf.png" width="480">

<img src="https://user-images.githubusercontent.com/1584163/32115573-57d68740-bb15-11e7-91cf-2f2019d8cd3f.png" width="480">

<img src="https://user-images.githubusercontent.com/1584163/32115580-5ad012cc-bb15-11e7-96b5-95086efd7859.png" width="480">

**Comment by kwasim** [comment]
Looks good to me overall. Just one comment and question.
- There can be many variables in a register and to provide search on each of them I believe will be cumbersome. Should we create a list of variables for each register that are searchable and allow user to configure from this predefined list?

**Comment by u-moosajee** [comment]
Just a suggestion: Is it possible to configure the user initials in such a way that if we tap on them a pop-up or something appears which allows you to switch users?

**Comment by rowo** [comment]
@alihabib @maimoonak @kwasim @u-moosajee @cagulas @keymane 

I've updated the screens and issue to reflect optimization for a 5" Android smartphone vs. tablet. As a result, in all registers, the limit is probably 3 columns. The other significant change is moving the top buttons into a dropdown. I will make changes to the other screens as we create issues and note changes from what you've seen.

> @kwasim: There can be many variables in a register and to provide search on each of them I believe will be cumbersome. Should we create a list of variables for each register that are searchable and allow user to configure from this predefined list?

I agree. Perhaps @keymane can shed some light on what's currently searchable in the existing ZEIR and we can think about limits.

> @u-moosajee: Just a suggestion: Is it possible to configure the user initials in such a way that if we tap on them a pop-up or something appears which allows you to switch users?

The user initials have been removed in favor of a back button to go back to the register list. To switch users, the logged in user goes to the home screen, clicks on the top right button and selects Log Out from the dropdown.

**Comment by keymane** [comment]
In ZEIR the searchable fields are first name, last name and zeir ID (Unique patient ID)

**Comment by cagulas** [comment]
I like Roger's suggestion in the original comment that the searchable fields should only be any of the fields that are displayed in the "Patient" column. 

@ndegwamartin @githengi is this possible?

**Comment by cagulas** [comment]
Actually, this is just first name, last name, and ID (same as ZEIR), because searching by age or gender doesn't make sense.

**Comment by cagulas** [comment]
Results from QA on 18 January (v0.0.4 alpha release):

- [ ] Is the push notification in each register that says "Presumptive Patients Register!" etc. necessary? I think we should remove this in the registers, as it seems a bit redundant; plus it seems to delay opening the register view.
- [ ] The extra options (3 white dots) button in the top right is not centered in its square.
- [ ] Remove the extra spaces between age and gender in the patient column. It should be "age[comma][space]gender".
- [ ] When I add a new patient in any of the registers then go back to the home screen, the number of patients shown in parentheses next to each register should automatically update. Currently, it seems you have to sync for this to update.
- [ ] When I use the search bar and start typing in a name ("Caro") the results column is suddenly extended and seems to show a lot of duplicate results.
- [ ] If we are removing the QR code option, let's make the search bar the full width of the screen. Change the label shown in the search bar to "Search name or ID" as per the mockups.
- [ ] PATIENT column header should be left-aligned, while the remaining column headers should be center-aligned.
- [ ] In the add result dropdown, let's change "Xpt" to "Xpe" to match the label that's shown in the result column.

**Comment by faith-mutua** [comment]
Results from QA on 22 January (v.0.0.4 alpha release):

- [ ] When I tap into the search bar then leave the page, the cursor on the search bar doesn't disappear. This also happens when I cancel the search results then tap anywhere else on the screen across all registers.

**Comment by cagulas** [comment]
Closing, this is done.
