### ISSUE TITLE
User configurable Home

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client-tbr#3]
Use [json2view](https://github.com/Avocarrot/json2view) to generate UI from json. This json view should be downloadable from opensrp server. 

- [ ] Get view from home.json for app which would be downloaded from server. 
- [ ] Render Login and/or Home page from home.json. 
- [ ] The Home should be register based where each item click navigates to a maingrid for that register
- [ ] Each register should be protected by a privilege that is drawn from TMM
- [ ] Other items should be available as buttons on a stack.

**Comment by cagulas** [comment]
@maimoonak Closing this, since new issues were created for implementation that I think duplicate these. Please reopen if needed.
