### ISSUE TITLE
Refactor tbr sync functionality to use location based sync

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-tbr#31]

**Comment by cagulas** [comment]
Blocked by https://github.com/OpenSRP/opensrp-client-tbr/issues/28.

**Comment by cagulas** [comment]
@ndegwamartin Based on the email discussion, it looks like we can sync by teamID for now, and hopefully add the flexibility later on to allow the user to choose at the beginning which method to sync on. I think we can close this issue, then, because sync by teamID is already in place, right?

**Comment by ndegwamartin** [comment]
right
