### ISSUE TITLE
Implement the Contacts section on the positive and in treatment patient detail views

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#38]
The Contacts section exists in both the Positive Patient and In Treatment Register patient detail views. This allows the user to add/view/screen contacts of the TB patient. Please reference this issue for background info: https://github.com/OpenSRP/tbr5/issues/45.

- [x] When a patient is diagnosed with TB and moves to the Positive Patient register, their detail view will have a blank contacts section:

![31580972-4e43483c-b12c-11e7-998f-f4f3cedefc0d](https://user-images.githubusercontent.com/3488986/32693037-d7f499e6-c734-11e7-9dfb-7c69ffa27bdf.png)

The "Add Contact" button launches the Add TB Contact form (https://ona.io/opensrp/45150/254493), where the user can add one or more contacts (uses a repeat group).

- [x] The contacts that are added in the Add TB Contact form appear as avatars in the index patient's contact details box. The initials are taken from the first name and last name fields in the form. The color of the avatar comes from the person's gender: male, female or 3rd gender. See [this issue](https://github.com/OpenSRP/opensrp-client-tbr/issues/49) for the color codes for the gender.

![31445473-1dbb807a-ae6c-11e7-8aae-32cbc34d4990](https://user-images.githubusercontent.com/3488986/32693130-6551f5b2-c736-11e7-9a7e-4cf763370447.png)

- [x] Tapping on any of the avatars opens the Contact Screening Form (https://ona.io/opensrp/45150/261997) for the user to screen that contact. This is similar to the Screening Form we saw in the Presumptive Register. The difference here is that you have already collected the basic demographic details of this person and linked them to an existing TB patient through the Add TB Contact form.

- [x] Add different icon indicators to the contact avatars to indicate different statuses, for instance:

A) 
![31445475-1dbdad82-ae6c-11e7-9938-d16683753a89](https://user-images.githubusercontent.com/3488986/32693173-421e43a6-c737-11e7-98f3-cf486ed3ed56.png)

B) 
![31445476-1dbe28b6-ae6c-11e7-8e0d-8dc5e936da8e](https://user-images.githubusercontent.com/3488986/32693188-a5bddbec-c737-11e7-9e6e-b3b07646d235.png)

C)
![31445478-1dc165f8-ae6c-11e7-8140-cc443e41018e](https://user-images.githubusercontent.com/3488986/32693189-b7851926-c737-11e7-94ea-30720325d5cf.png)

D) 
![31445477-1dbf8a30-ae6c-11e7-8409-5bfd6c84e9e4](https://user-images.githubusercontent.com/3488986/32693195-c788cf8e-c737-11e7-8005-920c41b97449.png)

**Comment by rowo** [comment]
@ndegwamartin 
![icon-contactscreen-check](https://user-images.githubusercontent.com/1584163/33108677-71ab34c2-cf0b-11e7-8540-99e3f58a21f4.png)
![icon-contactscreen-pos](https://user-images.githubusercontent.com/1584163/33108678-71bb6b26-cf0b-11e7-80a8-8fbf04769af7.png)
![icon-contactscreen-x](https://user-images.githubusercontent.com/1584163/33108679-71c59e52-cf0b-11e7-9b73-37a9c944dfc2.png)

**Comment by cagulas** [comment]
QA results:

- [ ] The app crashed when I selected the Contact Screening read-only form in the negative screened person's avatar the first time. Subsequently, the app didn't crash, but selecting the negative screened patient is very slow - it takes a second or two to open after tapping on the avatar.

**Comment by cagulas** [comment]
Lgtm
