### ISSUE TITLE
User configurable Datagrid

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client-tbr#4]
Use [json2view](https://github.com/Avocarrot/json2view) to generate UI from json. This json view should be downloadable from opensrp server.

- [ ] Get view from datagrid_name.json for given register which would be downloaded from server.
- [ ] The datagrid should be tied to a register defined in Home whose click triggers datagrid activity.
- [ ] Render Datagrid page from datagrid_name.json.
- [ ] Row items in datagrid should be populated from CE model and/or form submission
- [ ] Row item should also be able to trigger Form entry and / or Detail View
- [ ] A new person entry should also be allowable from UI
- [ ] Search should be dynamic and tied to CE and/or form submission
- [ ] Filters should be dynamic 
- [ ] Sort should be dynamic
- [ ] Service mode should be dynamic
- [ ] Paging should be available and page size should be configurable via datagrid json

**Comment by cagulas** [comment]
@maimoonak Closing this, since new issues were created for implementation that I think duplicate these. Please reopen if needed.
