### ISSUE TITLE
Implement the user configurable In-treatment Patients Register

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#40]
The in-treatment patients register screen is what you see when you select the third register listed on the home screen (https://github.com/OpenSRP/opensrp-client-tbr/issues/9).

![262364678](https://user-images.githubusercontent.com/3488986/33163249-9e342fc4-d03e-11e7-9322-1b9e8fb18b2e.png)

- [x] The name of the register is configurable - so what they name the register on the home screen should be displayed here as the register name.
- [x] Pressing the back button on the phone returns the user to the home screen. Back arrow does the same thing.
- [x] The search bar, the Scan QR code button, and the top right dropdown function the same way as the presumptive and positive patients registers. 
@kwasim @alihabib @maimoonak In this register, are we adding an option to register a patient directly in this register (i.e. bypassing the presumptive and positive registers)? If so, we will need the xlsform for this.
- [x] Patients get added to this register from the Positive Patients register (Treatment Initiation form: https://ona.io/opensrp/45150/252646).
- [x] If a patient gets added to the register, then the content that appears for them is determined by the columns that they choose to add to the register (~~@rowo to share the columns~~).
  Columns as of 27 Nov
  ![columns-anyregister](https://user-images.githubusercontent.com/1584163/33283948-6edec6e0-d37b-11e7-9810-1b63540a24e9.png)
  ![columns-intreatment](https://user-images.githubusercontent.com/1584163/33283949-6ef35128-d37b-11e7-86e3-c730299ddb9e.png)

**Comment by rowo** [comment]
Columns as of 27 Nov

![columns-anyregister](https://user-images.githubusercontent.com/1584163/33283948-6edec6e0-d37b-11e7-9810-1b63540a24e9.png)

![columns-intreatment](https://user-images.githubusercontent.com/1584163/33283949-6ef35128-d37b-11e7-86e3-c730299ddb9e.png)

**Comment by cagulas** [comment]
Results from QA on 19 January (v0.0.4 alpha release):

- [ ] Is the push notification in each register that says "In-treatment Patients Register!" etc. necessary? I think we should remove this in the registers, as it seems a bit redundant; plus it seems to delay opening the register view.
- [ ] The extra options (3 white dots) button in the top right is not centered in its square.
- [ ] Remove the extra spaces between age and gender in the patient column. It should be "age[comma][space]gender".
- [ ] When I add a new patient in any of the registers then go back to the home screen, the number of patients shown in parentheses next to each register should automatically update. Currently, it seems you have to sync for this to update.
- [ ] Let's remove the QR code button and make the search bar the full width of the screen. Change the label shown in the search bar to "Search name or ID" as per the mockups.
- [ ] PATIENT column header should be left-aligned, while the remaining column headers should be center-aligned.
- [ ] In the add result dropdown, let's change "Xpt" to "Xpe" to match the label that's shown in the result column.
- [ ] For the default app, can we have the followup column be the column on the far right and the results in the middle?
- [ ] The Follow-up column can be reduced in width I think. It looks too wide in relation to the results column.
- [ ] I think the schedules for follow-up are a bit off. Right now, if the follow-up visit is due today, it shows red, whereas another patient with a follow-up visit due tomorrow already shows blue. What should happen is that the follow-up visit reminder should only turn blue when it's due (the day it's due), then it turns red the day after (by default), but we are looking to whether or not we can make the overdue period configurable (check this issue: https://github.com/OpenSRP/opensrp-client-tbr/issues/64.
- [ ] The red overdue visit button should show the original due date. Right now, it shows red followup and no date.
- [ ] Can we change "Followup" to "Follow-up"?

Note: We'll need to add sort and filter options in the top right dropdown, but this is blocked for the time being until https://github.com/OpenSRP/opensrp-client-tbr/issues/45 is finalized.

**Comment by cagulas** [comment]
Closing. Will put new remaining issues in new issue.
