### ISSUE TITLE
Update the list of configurable columns for registers

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#46]
Suggestions from the 7 Dec call:

- [x] Add smear (only) result column
- If technically easy and there's time - add x-ray and culture columns as well **RW: let's wait to when there is time to reconsider, but I don't think this needs to be comped yet**
- [x] Remove diagnose with schedule column
- [x] Remove encounter column and add that info into the diagnose button column instead
- [x] Remove BMI column
- [x] Remove dropdown column 
- For in-treatment result column, xpert result would likely never be done again. Usually (for tb susceptible), only smears are done to track progress during the treatment phase **RW: no changes here, this is entirely configurable by the app creator. What I'm hearing with "likely" is that we don't want to remove the possibility of having it, but by default it shouldn't be there**
- Both pos and neg results should be shown for presumptive and positive registers
- [x] Don't need schedule for starting treatment column

Once the mockups are updated for any-register, presumptive-only, positive-only, and in-treatment only, send to IHS for annotation.

**Comment by rowo** [comment]
@cagulas these below look like they cover all of the updates?
![columns-any](https://user-images.githubusercontent.com/1584163/34026835-b26b84da-e126-11e7-8a79-d5d1ac22220f.png)
![columns-presump-pos](https://user-images.githubusercontent.com/1584163/34026839-b4d57410-e126-11e7-829c-655d4cabdf1b.png)
![columns-intreatment](https://user-images.githubusercontent.com/1584163/34026842-b6cd335c-e126-11e7-994b-7432f4562185.png)

**Comment by cagulas** [comment]
For presumptive diagnose column, I don't think encounter would be a common term used (it comes from OpenMRS, so the "Enc" might be confusing to people. If this is the screening date, maybe we can abbreviate to "Scr" or something like that?

@alihabib @kwasim thoughts?

**Comment by cagulas** [comment]
@alihabib @kwasim For the Treatment column, there is no field in the xlsform where the user inputs intensive vs. continuation, so I'm assuming this is based on a calculation of how long they've been on treatment? What is that automated calculation?

Also I note that the Regimen field in the form is a text field. Are we not having a dropdown list of medication regimens?

**Comment by cagulas** [comment]
@rowo for the In-treatment results column, is this intended to show only 1 latest result at a time? So if they have two results entered on the same day, only the last one entered is shown?

**Comment by cagulas** [comment]
@alihabib @kwasim Once we get feedback on the couple of questions above, I'll go ahead and create implementation issues to update the devs on all of the configurable columns throughout the app. Let us know if all of the above looks ok.

**Comment by kwasim** [comment]
for presumptive diagnose column, screening date makes sense to me as suggested by @cagulas which can be abbreviated to "scr date". It may fit into columns but I think that's okay.

for TB phases, for drug susceptible tb, first two months is considered an intensive phase followed by 4 months of continuation phase. I am not sure though if implementation varies from country to country. 

as for the regimen, I also think it should be a dropdown.

for Diagnose, diagnosis, results etc columns, I think showing dates (day/month) would be a better idea than say xd ago or xm ago @cagulas @alihabib what you guys think?

**Comment by u-moosajee** [comment]
@cagulas @rowo are these the updated mockups that need to be annotated?

**Comment by cagulas** [comment]
@kwasim ok great, thanks.

@u-moosajee I think Roger will post one more update, so maybe it's a good idea to wait for the final versions before annotating them? On a separate note, would you be able to update the xlsform to make the treatment regimen a dropdown with regimen options instead of a text field? 

@alihabib Should we automatically calculate intensive vs. continuation phase (first 2 months, then remaining 4 months) or would this vary by site?

**Comment by rowo** [comment]
@kwasim just to confirm, did you do "scr date" lowercase on purpose?

@kwasim any final decision on date format? 

I also came across an old issue, https://github.com/OpenSRP/tbr5/issues/47#issuecomment-337903427, where @alihabib recommends a schedule column/button for Smear that I never drew
 up — is this still applicable @kwasim @alihabib ?

**Comment by rowo** [comment]
I made the following updates:
- Changed all instances of "x days ago" to MM/DD/YYYY format
- Changed "Enc:" to "Scr Date:" on Diagnose column (except for Treatment column which I changed to "Month X" format)
- Edited typo on Treatment column to include regimen
- Changed DD/MM format on schedule buttons to DD/MM/YY
- Added a SMR Result column for smear schedule button

![col-1](https://user-images.githubusercontent.com/1584163/34369000-7b4f518e-ea86-11e7-891e-4617f6cb7561.png)

![col-2](https://user-images.githubusercontent.com/1584163/34369002-7c80e982-ea86-11e7-9a80-11d2e963d758.png)

![col-3](https://user-images.githubusercontent.com/1584163/34369005-7ef4168a-ea86-11e7-8337-d43a8bb7684d.png)

**Comment by u-moosajee** [comment]
@rowo hi roger, please view the attached annotated images for the register columns

@alihabib could you please advise on what dropdown options to add  for treatment regimen as suggested by Caroyln above

![anyregcolumn_annotated](https://user-images.githubusercontent.com/33152822/34435441-7fbd714e-ecaf-11e7-80ff-6cd000be55ff.jpg)
![intreatmentreg_annotated](https://user-images.githubusercontent.com/33152822/34435442-7ff8c08c-ecaf-11e7-91c6-a0cd73858286.jpg)
![specificregcolumns_annotated](https://user-images.githubusercontent.com/33152822/34435443-8030d5ee-ecaf-11e7-88c7-5bd5f4081f5f.jpg)

**Comment by githengi** [comment]
@alihabib Will the Smear Result due date be added to the Smear Result form?

**Comment by cagulas** [comment]
@u-moosajee can you please update the mockups with the variable names for the follow up and smear result schedules in the forms? Also the treatment column the phase of treatment and treatment regimen. Thanks.

**Comment by u-moosajee** [comment]
![tbr5 annotated image](https://user-images.githubusercontent.com/33152822/35030824-5255ff64-fb82-11e7-84d4-868455aebba8.jpg)


@cagulas please see the annotated mockup with the missing variable names incorporated

**Comment by cagulas** [comment]
Found a few issues with the columns, but I'll create a new issue and close this issue.
