### ISSUE TITLE
Add weight and BMI to in-treatment detail view

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#47]
Based on the 7 December call, BMI column is not needed, but tracking BMI and weight gain for in-treatment patients is important, so something to possibly add to the detail view.

**Comment by rowo** [comment]
Does this count as two modules — BMI and a weight if BMI isn't available?  If so, the below graphic could just be changed to weight.

![bmi](https://user-images.githubusercontent.com/1584163/33918242-59f07470-df80-11e7-9eb1-f14ba218fe3c.png)

Also for the height in the follow up form — is that pulled in automatically (because that value shouldn't change much for majority of people right?)? Otherwise could be a source of BMI error (ex: asking patient for height vs. taking).

**Comment by rowo** [comment]
Notes from email thread:

- Ali: The way I was thinking of handling the problem of height not being entered (potentially) was to use the latest height value that we have in the system to calculate BMI. If there is no height then BMI impossible and we show weight. So one or the other (as opposed to both)

**Comment by cagulas** [comment]
So based on the above, we show weight only unless a height value is entered, and we use that height to calculate all BMIs. If height is removed in a later visit, we still use the previous height to calculate BMI. If height is updated, we use the new height to calculate BMIs from that point on.

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
@githengi @ndegwamartin Changing this to an implementation issue now, based on the description and mockups in https://github.com/OpenSRP/opensrp-client-tbr/issues/47#issuecomment-353603822.

This is getting added to the in-treatment detail view only (not the other two registers). This section can be added in between the results comparison and contact sections on the detail view.

Weight and height are captured in the different registration forms and can also be added in the follow-up form.

Variables are `weight`, `height`, and `bmi` in the forms.

**Comment by ndegwamartin** [comment]
@rowo @cagulas for this view, how do we handle if there is no height either? I can see from the forms the height field is not 'required'

**Comment by cagulas** [comment]
hey @ndegwamartin See https://github.com/OpenSRP/opensrp-client-tbr/issues/47#issuecomment-353603822.

If no height is entered, it becomes a weight-only display.

**Comment by ndegwamartin** [comment]
@cagulas I think I meant to ask the other way round, that is **weight** is NOT required either. Also I forsee a scenario where the first follow up only height is entered, then on the second both height and weight are entered, then on the third only weight is entered and so on. How do we handle that then?

**Comment by cagulas** [comment]
As discussed, weight is being changed to a required field.

**Comment by cagulas** [comment]
Lgtm. Closing
