### ISSUE TITLE
Add color for third gender

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#49]
Green or yellow are fine to use (from Dec 7 call).

**Comment by rowo** [comment]
![avatar](https://user-images.githubusercontent.com/1584163/33906322-a1448f22-df4f-11e7-96aa-b62ace4a61c5.png)

F: #ec407a on #f9e3f9

M: #208cc5 on  #d3ebff

3rd: #408027 on #dcedc8

**Comment by mberg** [comment]
Do we need to add color for adults?

**Comment by rowo** [comment]
The value would be being able to identify contacts by initials and gender vs. just initials if the avatar doesn't exist, which will probably be the norm.

**Comment by rowo** [comment]
An alternative is a list of contacts with full names and a column for status.

**Comment by rowo** [comment]
@cagulas Perhaps Matt's comment makes sense to ask. For contacts, if we don't want to make gender a required field, we just need a "no gender defined" color which could just be the green.

**Comment by cagulas** [comment]
@rowo If green is for no gender defined, then what would 3rd gender color be? I don't understand what's being asked.

**Comment by rowo** [comment]
@cagulas 

The question would be: whether we want to allow no gender defined (or similarly not make gender a required field which would make adding contacts one less question faster) — and as a result, we would need to define a color for when that happens.

And if the above is the case, I'm suggesting that we could just use green for both no gender defined and third gender, if that's not too confusing or inappropriate.

**Comment by cagulas** [comment]
I looked at the forms again, and gender is a required field in both add contact and screening forms. For screening, IHS was saying it's good to know at minimum age and gender of those screened, so I think requiring gender is fine. The 3rd option is actually "Transgender" in the forms, not 3rd gender.

**Comment by alihabib** [comment]
Right... so the problem is that OpenMRS does not support a third gender
option and you can't  create a patient in OpenMRS without gender... so
gender undefined or not required won't work... so this has to be handled as
an observation. As an FYI there was a long conversation on OpenMRS about
this and the issue is so fundamental to the model that modifying it to
allow a 3rd or undefined gender that behaves in a way similar to the
current Male and Female options is a massive effort.

Ali

Ali Habib
Chief Executive Officer
Interactive Health Solutions
http://www.ihsinformatics.com

ali.habib@ihsinformatics.com

**Comment by rowo** [comment]
@alihabib Slightly confused now. I understand we should require a gender field/answer. But does the OpenMRS requirement mean it needs to be M or F, and we are not allowing a transgender answer? 

Or are we all good with just the additional color and people can answer Male, Female, or transgender/3rd/undefined?

**Comment by cagulas** [comment]
I think what @alihabib is saying is that we have to input M or F as the person attribute, which is required for the person to be added in OMRS, but we can also map this question to another observation field in OMRS, where the answer choice can be M, F, or Transgender.

@maimoonak How has IHS handled this previously? If Transgender is selected, do you map this to M or F in the person attribute required field?

**Comment by alihabib** [comment]
"I think what @alihabib <https://github.com/alihabib> is saying is that we
have to input M or F as the person attribute, which is required for the
person to be added in OMRS, but we can also map this question to another
observation field in OMRS, where the answer choice can be M, F, or
Transgender."

Exactly. An alternate is to have an observation that just shows up as a
checkbox for transgender (as opposed to a choice for M, F, Transgender)

Ali Habib
Chief Executive Officer
Interactive Health Solutions
http://www.ihsinformatics.com

ali.habib@ihsinformatics.com
