### ISSUE TITLE
User configurable Detail View

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-client-tbr#5]
Use [json2view](https://github.com/Avocarrot/json2view) to generate UI from json. This json view should be downloadable from opensrp server.

- [ ] Get view from detailview_name.json for given item in datagrid which would be downloaded from server.
- [ ] The detailveiw should be tied to a row item in datagrid defined in Datagrid whose click triggers detail view activity.
- [ ] Render Detail view page from detailview_name.json
- [ ] Items in detail view should be populated from CE model and/or form submission
- [ ] Items should also be able to trigger Form entry and / or other Detail View and / or other registers

**Comment by cagulas** [comment]
@maimoonak Closing this, since new issues were created for implementation that I think duplicate these. Please reopen if needed.
