### ISSUE TITLE
Update Xpert results in configurable columns

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#52]
I think it would be helpful to show the different options for Xpert results in the configurable column, because I think there might be a spacing issue, so hopefully you can tell us.

I'm referring to comments from Wasim in https://github.com/OpenSRP/opensrp-client-tbr/issues/34#issuecomment-346312569.

- [x] In the Xpert result form, the MTB result answer choices (and the suggested label for the configurable column in parentheses) are:
- `detected` (+ve)
- `not_detected` (-ve)
- `indeterminate` (?)
- `error` (err)
- `no_result` (No result)

Note 1: RIF result is only recorded if MTB is detected (+ve). So, if MTB result is any other answer choice above, then RIF result should not be displayed in the column (and the MTB result can be the full width of the column).

Note 2: If error is selected (err), the error code should also be displayed. According to Wasim, the error code is usually four digits and can be displayed in parentheses.

- [x] The RIF result answer choices (and the suggested label for the configurable column in parentheses) are:
- `detected` (+ve)
- `not_detected` (-ve)
- `indeterminate` (?)
~~- `error` (err)~~

Note 3: Again, these are only displayed if MTB result is detected (+ve). 

~~Note 4: There is no error code collected for RIF result in the form, so this would just be "err" alone.~~ CG: Error for RIF was removed in the XLSForm it looks like.

@alihabib and @kwasim Does the above sound ok to you. I am basing this off the latest xlsform for Xpert result uploaded to Ona.

**Comment by alihabib** [comment]
This all looks good. If we can have "err" instead of "e" for error I think
that would be more clear.

Ali

Ali Habib
Chief Executive Officer
Interactive Health Solutions
http://www.ihsinformatics.com

ali.habib@ihsinformatics.com

**Comment by cagulas** [comment]
Thanks @alihabib, I updated the issue.

**Comment by rowo** [comment]
![xpertresults](https://user-images.githubusercontent.com/1584163/34733225-a6504622-f535-11e7-99be-4a5467c5e010.png)

Here's a look at what Xpert results might look like in an Xpert results-only column and in the results column Xpe line. The description in the first comment covers how to determine what shows up, so I tried just to illustrate the extreme cases.

Also note **+ve** will always show up in #c30000 to highlight the positive result whether it's MTB or RIF. Otherwise, negative and other results show up in #191919 and the MTB, RIF and Xpe show up in #737373.

**Comment by cagulas** [comment]
Looks great, thanks @rowo. Changing this to an implementation issue now and assigning @githengi and @ndegwamartin. Please note how the results are shown differently in Xpert result only column vs. the general results column.

**Comment by githengi** [comment]
@cagulas @rowo When is  _"No Result"_ is to be displayed

**Comment by rowo** [comment]
@githengi I took it to mean that there is a "No result" choice in the Xpert result form for MTB result.

**Comment by alihabib** [comment]
@Roger: That's right. "No Result" can be the outcome of an Xpert test

Ali

Ali Habib
Chief Executive Officer
Interactive Health Solutions
http://www.ihsinformatics.com

ali.habib@ihsinformatics.com

**Comment by githengi** [comment]
@alihabib could the "No Result" outcome kindly be added to the current GeneXpert Enketo form

**Comment by cagulas** [comment]
@u-moosajee @kwasim The no result is already there, but the list name is missing in the xlsform, which means this option is not showing up right now. Umme, can you please fix this?

**Comment by u-moosajee** [comment]
@cagulas ive fixed it and updated the form

**Comment by cagulas** [comment]
Lgtm, closing.
