### ISSUE TITLE
Update form specs with addition of HIV status question

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-tbr#59]
I saw in the HIV question in the treatment initiation form and just wanted to make sure we're not showing that flag or label anywhere. 

If that is the case, maybe at the end of forms where the answer is something positive like that (i.e. has HIV), there is a note that says that the HIV data point is recorded but will not show up except for if the form is accessed.

**Comment by cagulas** [comment]
@u-moosajee - In the treatment initiation form, there is a choice option in the choices sheet that says `hiv_results` but no corresponding question in the survey sheet. Is the question missing, or should the hiv_results options be removed from the choices sheet?

**Comment by u-moosajee** [comment]
Ideally, I think we should not have the hiv question in the treatment initiation.

@alihabib please advice whether we should proceed with removing the hiv_results choices from the choices sheet.

**Comment by u-moosajee** [comment]
@cagulas @rowo After discussing with @alihabib I have added HIV questions at each point when a patient is added to the program, i.e. screening, add positive and add in-tx patient forms. You can find the updated versions of the XLS forms here: https://ona.io/opensrp/45150#

**Comment by cagulas** [comment]
@u-moosajee Thanks for this. I have noted that HIV status is only recorded if they answer yes to having an HIV test in the last 6 months. What about other HIV patients who were tested previously and are HIV positive? We may not necessarily capture those individuals with this skip logic. Is the intention to know every patient's HIV status? Then modifying the skip logic or wording of the question might be needed. Also, just to bear in mind that we aren't showing a patient's HIV status anywhere in the app right now, so this data would be in the back-end only (and available for reporting), but wouldn't be visible in the app. Is this ok or needs to be shown?

**Comment by rowo** [comment]
Just to note also — I don't think we have the flexibility to add anything super complex as far as showing the HIV label in this project (show HIV status if user writes password for example). 

So something straightforward where it's shown in the form if they pull it up would be fine — with a kind of XLSForm-generated note suggested in the [first comment](https://github.com/OpenSRP/opensrp-client-tbr/issues/59#issue-284616663). Actually, I think the HIV question(s) will appear this way regardless because it's the same as if implementers add new questions to forms — pulling up the form would be the only way to see the question again.

**Comment by alihabib** [comment]
Hi all,

We don't need the HIV status to show up on the registers. Having it be in
the forms (and therefore available in reports at the OpenMRS/dashboard end)
is sufficient.

Ali

-- Sent from my mobile. Please excuse typos and brevity

**Comment by cagulas** [comment]
@rowo Yes, good point. At this stage, we'll probably want to leave it at this.

@u-moosajee does this sound ok to you?

**Comment by cagulas** [comment]
@alihabib great, sounds good.

@rowo I'm reassigning and relabeling the issue for implementation now, as I think there's nothing further we need to do, but @githengi and/or @ndegwamartin will need to update the form definition with this addition now.

**Comment by cagulas** [comment]
@alihabib Great, thanks. As to the question about the wording of the question, is this fine, or should we change the wording, so that it captures HIV status for all patients, not only the ones that had a test within the last 6 months? Also, should this question be in the screening form or only when the patient is diagnosed with TB?

**Comment by alihabib** [comment]
Let me get back to you on that one by tomorrow

-- Sent from my mobile. Please excuse typos and brevity

**Comment by rowo** [comment]
Please note, it will be in the forms so it will be accessible in the app. In case that has privacy implications.

**Comment by u-moosajee** [comment]
@cagulas @rowo ive modified the HIV questions to remove "in the last 6 months" part in the screening, contact screening, add positive patient and add in-treatment patient forms. Now it just asks "Have you been tested for HIV in the past?" If yes, what is your HIV status. 

You can find the updated forms here: https://ona.io/opensrp/45150#

**Comment by cagulas** [comment]
@u-moosajee @alihabib Should this be asked for everyone who gets screened or only for positive TB patients, i.e. should we keep this in the screening form or move it to the TB diagnosis form?

**Comment by u-moosajee** [comment]
@cagulas according to the conversation with @alihabib HIV question is asked at each point a patient in being registered into the program (i.e. screening, add positive patient and add intreatment patient forms)

**Comment by cagulas** [comment]
@u-moosajee ok cool, thanks.

**Comment by cagulas** [comment]
@githengi @ndegwamartin Ok, this is ready for implementation now. I've updated the title of the issue. The forms that were updated were: 

Screening form: https://ona.io/opensrp/45150/273474#/settings
Contact screening form: https://ona.io/opensrp/45150/273473#/settings
Add positive TB patient form: https://ona.io/opensrp/45150/273471
Add in-treatment TB patient form: https://ona.io/opensrp/45150/273470

The following three fields were added to the above forms:
`hiv_test`
`hiv_date`
`hiv_results`

**Comment by cagulas** [comment]
@githengi Is this done?  I see the questions in the forms in the app. Please close if done.

**Comment by githengi** [comment]
Questions updated. This can be closed
