### ISSUE TITLE
Implement local login when offline

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-tbr#62]
- [x] Implement local app login when offline

- [x] Local login possible when one after atleast one remote login

- [x] Local login possible for only the same user

- [x] Store login page configuration in shared preferences

- [x] Only Store login page configuration in shared preferences if sqlite database is not already created

**Comment by cagulas** [comment]
@githengi How to QA this issue? What steps to follow?

**Comment by githengi** [comment]
Once you have successfully logged in. Disconnect network(wifi and data). The app should be able to log in.

Also changes to login user configurations should apply even before login.

**Comment by cagulas** [comment]
Cool. lgtm
