### ISSUE TITLE
Implement the user configurable login screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#8]
The login screen allows the user to log in to the TBR application using their assigned credentials. During first login, the configurable app files will download from the server and be installed on the app.

**Not Configurable**
- [x] The Settings menu in the top right is required. This is where the user will need to enter the server url to download their app's configurable files. First time login should fail if the server url is not specified in the app settings.
- [x] Username and password fields and log in button are required and should appear as is.
- [x] Version and build date are required and should appear as is. **RW edit: text color = #FFFFFF at 60% opacity ~~new color values for this text needs to be defined so that it works with any dark background. This will be a translucent white.~~**
- [x] Powered by OpenSRP on the bottom is required and should appear as is. **RW edit: new image is attached. "Powered by" text needs to be changed to #FFFFFF at 60% opacity ~~this image will need to be updated so it works with any dark background image.~~**

**Configurable**
- [x] The background color of the login screen is configurable, but by default, it will be the OpenSRP blue gradient.
- [x] Logo and app name are configurable. We should probably set the size of each though. For the default app, the app name will be "TB REACH" and the app logo will be determined by https://github.com/OpenSRP/tbr5/issues/46. **RW question: @keymane I know the logo icon is an image, but is the logotype also an image? Is it possible to have a single image size and say whatever logo PNG should be that size?**
- [x] Show password checkbox is configurable. They can include this option or not. If they include, checking the box will show the password, but it should by default be unselected. If they do not choose to have this option, the password field is hidden always (current behavior of ZEIR app).

![login](https://user-images.githubusercontent.com/1584163/32496077-01edd836-c396-11e7-8086-662dd1f479fa.png)

**Comment by keymane** [comment]
@rowo 
1. The background is usually a gradient which consists of a start color, end color and angle
2. The logo type is usually an image. Text views may require customization. We can have logo PNGs of the same size that have the icon and the app name

**Comment by rowo** [comment]
@githengi @ndegwamartin 
Here's the logo image. Will add the OpenSRP logo shortly.

![login-logo](https://user-images.githubusercontent.com/1584163/31407158-d92889c0-add1-11e7-81ac-46c41c9edf23.png)

**Comment by rowo** [comment]
@githengi @ndegwamartin I updated the above screen with a phone version. Not sure if the current ZEIR already handles this okay, but it just means that the text boxes and graphics will be larger so they are clickable and are visible.

**Comment by cagulas** [comment]
Results from QA on 19 January (v0.0.4 alpha release):

- [ ] Cursor does not appear until you start typing in the username and password. Then the cursor that does appear is white, so it's hard to see where it is. Change the cursor color to something darker.
- [ ] Where did the app icon come from? The name of the app is also missing. Should it be required to have an app logo and app name for the login page?

**Comment by rowo** [comment]
For point two, Ona will create a new "default" logo. I think it's okay to be removed or replaced. 

App name should be required.

**Comment by cagulas** [comment]
"Logo and app name are configurable. We should probably set the size of each though. For the default app, the app name will be "TB REACH" and the app logo will be determined by OpenSRP/tbr5#46. RW question: @keymane I know the logo icon is an image, but is the logotype also an image? Is it possible to have a single image size and say whatever logo PNG should be that size?"

I took that (from first comment in this issue) to mean app logo and name are still separate.

@rowo can you weigh in here?

**Comment by rowo** [comment]
@cagulas The logo icon and logotype are comprised of a single PNG image file. It is a square and looks like this:
<img width="615" alt="screen shot 2018-01-19 at 5 06 09 pm" src="https://user-images.githubusercontent.com/1584163/35154368-174c7820-fd3b-11e7-9fcd-b870294e97a0.png">
(everything inside the black border)

My approach around point 2 in https://github.com/OpenSRP/opensrp-client-tbr/issues/8#issuecomment-358883455 are: 
- If someone doesn't want to use anything other than the default logo icon and logotype (currently the above placeholder but to be finalized in https://github.com/OpenSRP/tbr5/issues/46) then they will have to edit that image. Organizations are free to edit it in any way they want. 
- An app name is required, but it won't be reflected in this image. If they change the app name, they'll have to update the logo image and change the name. At that point, they can just replace the logotype part of the image or the entire thing.

**Comment by cagulas** [comment]
@rowo Ok thanks. So does that mean there is no space for app name on the login screen? In other words, it is up to them to make sure the app name is included in the logo image; otherwise, if they only have the app logo, then there won't be an app name that appears on the login page?

**Comment by rowo** [comment]
@cagulas yes that was the idea — it is up to them to make sure the app name is included in the graphic. We could approach it a user-defined way (login screen app name is defined somewhere and we render it with some styling),  but it's much more variable that way (we'd have to deal with or control long and short names, line breaks, extreme cases, etc.). 

With this approach, they have an image area they are free to do anything with. The default app will have both and serve as a template.

**Comment by cagulas** [comment]
This is done, closing.
