### ISSUE TITLE
Implement the user configurable home screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-tbr#9]
The home screen is where the user lands after they log in to the app (https://github.com/OpenSRP/opensrp-client-tbr/issues/8). From the home screen, they can select one of the registers to open. They can also force a sync in between automatic attempts.

**Not Configurable**
- [x] The app can have any or all of the 3 registers (presumptive, positive, and in-treatment). The app must have at least one of these registers and cannot have more than these 3 registers.
- [x] The number of patients is shown in parentheses next to each register name. 
- [x] Last sync date and time is shown at the bottom. The sync button allows the user to force a sync in between automatic attempts.
- [x] The register icons are not configurable. If they include that particular register in the app, that is the icon that would go with it.
- [x] The red flag displaying the number 2 is the number of patients in that register who have a currently due or overdue service schedule.
- [x] The RW shows the initials of the user who is logged in.
- [x] The app name appears at the top. This is configurable, case-sensitive, and takes the name of the app that is displayed on the login screen.
- [x] The Settings button on the top right is required and takes the user to settings menu (https://github.com/OpenSRP/opensrp-client-tbr/issues/10).  

**Configurable**
- [x] The names of the registers are configurable.

![home](https://user-images.githubusercontent.com/1584163/32496023-de360526-c395-11e7-9618-b19e6bea7f56.png)

**Comment by rowo** [comment]
@ndegwamartin 

![icon-home-book-diagnosed](https://user-images.githubusercontent.com/1584163/31405925-8129c5da-adcd-11e7-946d-2e720f27ad2c.png)
![icon-home-book-intreatment](https://user-images.githubusercontent.com/1584163/31405926-813a8118-adcd-11e7-9c8a-3c57c1658b9e.png)
![icon-home-book-presumptive](https://user-images.githubusercontent.com/1584163/31405927-81461b04-adcd-11e7-8eec-77a31bfbdcb1.png)
![icon-home-refresh](https://user-images.githubusercontent.com/1584163/31405928-8151f12c-adcd-11e7-9c38-9a3a070d9b5f.png)

**Comment by rowo** [comment]
@ndegwamartin I updated the above screens with phone versions. Basically just means the text is bigger.

**Comment by cagulas** [comment]
Results from QA on 19 January (v0.0.4 alpha release):

- [ ] The circle containing the user initials should align with the register icons I think.

**Comment by cagulas** [comment]
This is done, closing.
